services:
  # Jaeger for distributed tracing
  jaeger:
    image: jaegertracing/all-in-one:1.35
    container_name: jaeger
    ports:
      - "16686:16686"    # UI
      - "14268:14268"    # HTTP for spans
      - "14250:14250"    # gRPC for spans
      - "6831:6831/udp"  # UDP for spans
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"  # UI
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  # Grafana for metrics visualization
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  # UI
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  grafana-data:
  postgres-data: