version: '3.7'

services:
  sentry:
    image: sentry:latest
    platform: linux/amd64
    container_name: sentry
    restart: always
    environment:
      SENTRY_SECRET_KEY: gxv7-ucv)(t1suxz&_xdisp(9_z5vem(k9!64x&mxto^@j@b@w
      SENTRY_EMAIL_HOST: smtp.yourdomain.com
      SENTRY_EMAIL_PORT: 587
      SENTRY_EMAIL_USER: youremail@yourdomain.com
      SENTRY_EMAIL_PASSWORD: yourpassword
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_REDIS_HOST: redis
      SENTRY_DB_NAME: sentry
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentrypassword
      SENTRY_TSDB: 'sentry.tsdb.redis.RedisSnubaTSDB'
    ports:
      - "9000:9000"
    depends_on:
      - postgres
      - redis
      - snuba
    networks:
      - sentry_network

  postgres:
    image: postgres:13
    container_name: sentry_postgres
    restart: always
    environment:
      POSTGRES_DB: sentry
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: sentrypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sentry_network

  redis:
    image: redis:6
    container_name: sentry_redis
    restart: always
    networks:
      - sentry_network

  snuba:
    image: getsentry/snuba:latest
    container_name: snuba
    restart: always
    environment:
      SENTRY_REDIS_HOST: redis
    depends_on:
      - redis
    networks:
      - sentry_network

  cron:
    image: sentry:latest
    container_name: sentry_cron
    platform: linux/amd64
    command: run cron
    restart: always
    environment:
      SENTRY_SECRET_KEY: gxv7-ucv)(t1suxz&_xdisp(9_z5vem(k9!64x&mxto^@j@b@w
      SENTRY_EMAIL_HOST: smtp.yourdomain.com
      SENTRY_EMAIL_PORT: 587
      SENTRY_EMAIL_USER: youremail@yourdomain.com
      SENTRY_EMAIL_PASSWORD: yourpassword
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_REDIS_HOST: redis
      SENTRY_DB_NAME: sentry
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentrypassword
      SENTRY_TSDB: 'sentry.tsdb.redis.RedisSnubaTSDB'
    depends_on:
      - sentry
    networks:
      - sentry_network

  worker:
    image: sentry:latest
    container_name: sentry_worker
    platform: linux/amd64
    command: run worker
    environment:
      SENTRY_SECRET_KEY: gxv7-ucv)(t1suxz&_xdisp(9_z5vem(k9!64x&mxto^@j@b@w
      SENTRY_EMAIL_HOST: smtp.yourdomain.com
      SENTRY_EMAIL_PORT: 587
      SENTRY_EMAIL_USER: youremail@yourdomain.com
      SENTRY_EMAIL_PASSWORD: yourpassword
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_REDIS_HOST: redis
      SENTRY_DB_NAME: sentry
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentrypassword
      SENTRY_TSDB: 'sentry.tsdb.redis.RedisSnubaTSDB'
    restart: always
    depends_on:
      - sentry
    networks:
      - sentry_network

networks:
  sentry_network:
    driver: bridge

volumes:
  postgres_data:
